### ISSUE TITLE
Display P3-v4 has different whitepoint and chromatic adaptation matrix than Apple Display P3 profile

### ISSUE THREAD

**Issue by bartzy** [saucecontrol/Compact-ICC-Profiles#7]
Hi!

Thanks for this extremely helpful repository.

I'm trying to understand the reason for differences in values between Display P3-v4 in this repo, and the official "Display P3" ICC profile shipped with macOS by Apple (from 2017).

The WP changes:
![image](https://user-images.githubusercontent.com/167339/137314586-629b849f-2445-4dff-ad89-a596fb6c3cc1.png)

The chromatic matrix changes:
![image](https://user-images.githubusercontent.com/167339/137314626-c3fb479c-aad5-4033-a723-d077eb08da19.png)

Is this on purpose and Apple's profile is wrong in some way?

Thanks again!

**Comment by bartzy** [comment]
Thank you for the detailed information.

I'm not sure I completely understand, but you mean that there's very little functional difference between the profiles because CMSs actually use the chromatic adaptation matrix and not the media whitepoint anyway? Isn't the chromatic adaptation matrix different between the profiles as well though?
Realistically if I'm targeting iOS only device, should I just use Apple's profile even if it's wrong?

On another note and a bit unrelated - I'm trying to understand how to best configure ffmpeg and x265 to encode a video with Display P3, and I'm having a bit of trouble understanding what are the different flags I should use. Right now I'm using:
`-pix_fmt yuv420p10le -colorspace bt2020nc -color_trc bt2020-10 -color_primaries smpte432 -x265-params "colorprim=smpte432:transfer=bt2020-10:colormatrix=bt2020nc:master-display=""G(13250,34500)B(7500,3000)R(34000,16000)WP(15635,16450)L(10000000,1)""`
But I'm pretty sure it's wrong.
If this is completely unrelated to this repo, feel free to ignore it :)

Thanks!

**Comment by saucecontrol** [comment]
Right, the `wtpt` will be ignored and will be calculated from the `chad` by most software *if* it needs to perform an absolute colorimetric mapping, but even that will never actually happen as it's not a valid use for a display profile.  For display purposes, the primary colorants and curve are all that matter, so you can feel safe in using the two profiles interchangeably.

I'm not yet familiar with x265's color settings, so I'm afraid you're on your own there ;)

**Comment by bartzy** [comment]
I see. So what's the point in stating the Apple chose D65 for Display P3 and not DCI-P3 white illuminant?
What purposes does it serve? If all the primary colors add up to D50 white, where D65 in P3 is being "used"?

Thanks!

**Comment by ValZapod** [comment]
> there actually is no exact conversion

Defined in ICCv2/v4. In ICCmax there is now a defined conversion for any white point in Profile Connection Space, spec was done last year based on that crazy dissertation from Max Durac...

> So in summary, Apple's `wtpt` tag is wrong according to the ICC spec, but their `chad` value is fine although not as good as mine _if_ it were ever used by anyone, which it probably won't be.

Yeah. There is also a problem that display profile is used for what should be an input profile (?) at least there is such a problem in part one JPEG 2000... Part two supports display profiles too.

**Comment by ValZapod** [comment]
> But I'm pretty sure it's wrong.

Of course it is wrong, using mastering display for SDR?? What? LOL. ffmpeg -vf zscale should be used for actual conversion. But yeah, -pix_fmt yuv420p10le -colorspace bt2020nc -color_trc bt2020-10 -color_primaries smpte432 are correct, those just tag, not convert. bt.2020-10 is just (100% the same) BT.709 transfer, so SDR transfer, so SDR content. Next, smpte432 is Display P3, so correct. Next, colorspace is indeed better be bt2020nc, but maybe you would want to use RGB...

Do give a normal command line I need what stuff is in source file though.
